### ISSUE TITLE
Rendering broken in Unity 5

### ISSUE THREAD

**Issue by edwonedwon** [kennux/TressFXUnity#1]
Hello,

I'm interested in trying out the project. I download and it doesn't seem to render in Unity 5 properly (it's flashing alot)

I have an Nvidia GTX 970, perhaps that's the reason?

**Comment by kennux** [comment]
Hey,

There's currently a complete rewrite of tressfx ongoing in private.
Once it's done, this repo will be updated aswell as my blog will http://kennux.net.

Stay tuned :)

**Comment by edwonedwon** [comment]
Thanks Kenneth,

Do you have a mailing list I can subscribe to?

**Comment by kennux** [comment]
Hey,
There is no mailing list, just check the blog all 1-2 weeks :P

**Comment by kennux** [comment]
New tressfx version released
