### ISSUE TITLE
Problem with importing OBJ

### ISSUE THREAD

**Issue by cesaroncalves** [kennux/TressFXUnity#3]
Hello,
I have encountered an issue when importing the asset from Blender to Unity.
I'm following the tutorial present in the documentation with a custom asset, it seems that every time I import any .obj from blender to tressFX (hair from OBJ) all values return 0.

Here's the result.

![2017-02-09](https://cloud.githubusercontent.com/assets/21956254/22807032/deb945c4-ef1c-11e6-8940-8f432122be59.png)

(Blender 2.78, Unity 5.5)

**Comment by kennux** [comment]
Can you attach the obj file to this issue?
